In [1]:
import numpy

In [2]:
def scaryMatrix(nrows):
    m = numpy.zeros((nrows, nrows))
    for i in range(1, nrows - 1):
        m[i][i] = 10
        m[i][i-1] = m[i][i+1] = 1
    m[0][0] = 10
    m[0][1] = 1
    for i in range(nrows):
        m[nrows-1][i] = 1
    return m

In [3]:
def s(nrows):
    m = scaryMatrix(nrows)
    return m, numpy.linalg.solve(m, range(1, nrows+1))

In [4]:
m, a = s(100)

In [5]:
m.dot(a)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [6]:
a

array([ 8.33333333e-02,  1.66666667e-01,  2.50000000e-01,  3.33333333e-01,
        4.16666667e-01,  5.00000000e-01,  5.83333333e-01,  6.66666667e-01,
        7.50000000e-01,  8.33333333e-01,  9.16666667e-01,  1.00000000e+00,
        1.08333333e+00,  1.16666667e+00,  1.25000000e+00,  1.33333333e+00,
        1.41666667e+00,  1.50000000e+00,  1.58333333e+00,  1.66666667e+00,
        1.75000000e+00,  1.83333333e+00,  1.91666667e+00,  2.00000000e+00,
        2.08333333e+00,  2.16666667e+00,  2.25000000e+00,  2.33333333e+00,
        2.41666667e+00,  2.50000000e+00,  2.58333333e+00,  2.66666667e+00,
        2.75000000e+00,  2.83333333e+00,  2.91666667e+00,  3.00000000e+00,
        3.08333333e+00,  3.16666667e+00,  3.25000000e+00,  3.33333333e+00,
        3.41666667e+00,  3.50000000e+00,  3.58333333e+00,  3.66666667e+00,
        3.75000000e+00,  3.83333333e+00,  3.91666667e+00,  4.00000000e+00,
        4.08333333e+00,  4.16666667e+00,  4.25000000e+00,  4.33333333e+00,
        4.41666667e+00,  

In [7]:
m[0, 0]

10.0

In [8]:
m[0][0]

10.0

In [9]:
numpy.linalg.eig(m)

(array([ 0.8998885 , 12.0075607 , 11.99605346, 11.99401613, 11.9842294 ,
        11.97861784, 11.9645745 , 11.95516941, 11.93716632, 11.83886048,
        11.85955297, 11.88512613, 11.923951  , 11.90211303, 11.8096541 ,
        11.78534142, 11.75261336, 11.72478227, 11.58353003, 11.61803399,
        11.54102649, 11.50339507, 11.45793725, 11.65742304, 11.41733447,
        11.36909421, 11.22881673, 11.27484798, 11.1755705 , 11.12710336,
        11.07165359, 11.02094897, 10.96350735, 10.91077232, 10.85155858,
        11.68865585, 10.68010491, 10.73624911, 10.61803399, 10.5605241 ,
        10.49737977, 10.43873737, 10.37476263, 10.31522517, 10.19047477,
        10.12558104, 10.06497836, 10.        ,  9.93923108,  8.0009882 ,
         8.00394654,  8.0088879 ,  8.0157706 ,  9.87441896,  8.02465607,
         8.0354255 ,  8.04823035,  9.81372911,  8.06283368,  9.44363079,
         9.38196601,  9.32402363,  9.26375089,  8.09788697,  8.11839381,
         8.14044703,  9.50262023,  9.20708966,  8.1