In [142]:
import numpy

class GaussMatrix:

    def __getitem__(self, index):
        if isinstance(index, tuple):
            i = index[0] - 1
            j = index[1] + self.n
            return self.m[i, j]
        else:
            return self.m[index - 1]

    def __setitem__(self, index, value):
        if isinstance(index, tuple):
            i = index[0] - 1
            j = index[1] + self.n
            self.m[i, j] = value
        else:
            self.m[index - 1] = value

    def __init__(self, nrows):
        self.n = nrows
        self.m = numpy.zeros((nrows, 2 * nrows + 1))
        
        for i in range(1, nrows + 1):
            self[i, -i] = 1



    
    def forwardGauss(self):
        for i in range(1, self.n + 1):

            ii = self[i, i]
            self[i] /= ii

            for i_ in range(i + 1, self.n + 1):
                i_i = self[i_, i]
                self[i_] -= self[i] * i_i
                
    def backwardGauss(self):
        for i in range(self.n, 0, -1):
            for i_ in range(i-1, 0, -1):
                i_i = self[i_, i]
                self[i_] -= self[i] * i_i

    
    def solveGauss(self):
        self.forwardGauss()
        self.backwardGauss()
        return [self[i, 0] for i in range(1, self.n+1)]


In [148]:
class Matrix:
    def __getitem__(self, index):
        if isinstance(index, tuple):
            i = index[0] - 1
            j = index[1]
            return self.m[i, j]
        else:
            return self.m[index - 1]

    def __setitem__(self, index, value):
        if isinstance(index, tuple):
            i = index[0] - 1
            j = index[1]
            self.m[i, j] = value
        else:
            self.m[index - 1] = value

    def __init__(self, n):
        self.n = n
        self.m = numpy.zeros((n, n + 1))



    def norm(self):
        sumofmodulesarray = []

        for i in range(1, self.n + 1):
            sumofmodules = 0

            for j in range(1, self.n + 1):
                sumofmodules += abs(self[i, j])
            sumofmodulesarray.append(sumofmodules)

        return max(sumofmodulesarray)

    def dot(self, x):
        x_ = [0] + x
        return self.m.dot(x_)

In [149]:
class LinearSystem:
    def __getitem__(self, index):
        return self.source.__getitem__(index)
    def __setitem__(self, index, value):
        self.source.__setitem__(index, value)

    def __init__(self, n):
        self.n = n
        self.source = Matrix(n)

    def solveGauss(self):
        self.g = GaussMatrix(self.n)

        for i in range(1, self.n + 1):
            for j in range(0, self.n + 1):
                self.g[i, j] = self[i, j]
        
        ans = self.g.solveGauss()

        self.inverse = Matrix(self.n)
        for i in range(self.n+1):
            for j in range(self.n+1):
                self.inverse[i, j] = self.g[i, -j]
        return ans

    def conditionNumber(self):
        if not hasattr(self, "inverse"):
            self.solveGauss()
        return self.source.norm() * self.inverse.norm()


In [150]:
def scaryMatrix(nrows):
    m = LinearSystem(nrows)

    for i in range(2, nrows):
        m[i, i] = 10
        m[i, i-1] = m[i, i+1] = 1
    m[1, 1] = m[nrows, nrows] = 10
    m[1, 2] = m[nrows, nrows - 1] = 1

    for i in range(1, nrows+1):
        m[i, 0] = i
    return m

In [151]:
s = scaryMatrix(100)
s.solveGauss()

[0.08333333333333334,
 0.16666666666666666,
 0.24999999999999997,
 0.3333333333333333,
 0.4166666666666667,
 0.5,
 0.5833333333333334,
 0.6666666666666666,
 0.75,
 0.8333333333333334,
 0.9166666666666667,
 1.0000000000000002,
 1.0833333333333335,
 1.1666666666666667,
 1.25,
 1.3333333333333335,
 1.4166666666666667,
 1.5000000000000002,
 1.5833333333333335,
 1.6666666666666667,
 1.7500000000000002,
 1.8333333333333337,
 1.916666666666667,
 1.9999999999999998,
 2.0833333333333335,
 2.1666666666666665,
 2.2500000000000004,
 2.3333333333333335,
 2.4166666666666665,
 2.5,
 2.583333333333333,
 2.666666666666667,
 2.75,
 2.833333333333333,
 2.916666666666667,
 3.0,
 3.083333333333334,
 3.1666666666666665,
 3.25,
 3.3333333333333335,
 3.416666666666666,
 3.5000000000000004,
 3.583333333333333,
 3.6666666666666674,
 3.7499999999999996,
 3.8333333333333335,
 3.916666666666667,
 4.0,
 4.083333333333333,
 4.166666666666667,
 4.25,
 4.333333333333334,
 4.416666666666666,
 4.5,
 4.583333333333334,
 

In [152]:
s.conditionNumber()

1.5

In [136]:
m = scaryMatrix(5)
m.source.m

array([[ 1., 10.,  1.,  0.,  0.,  0.],
       [ 2.,  1., 10.,  1.,  0.,  0.],
       [ 3.,  0.,  1., 10.,  1.,  0.],
       [ 4.,  0.,  0.,  1., 10.,  1.],
       [ 5.,  0.,  0.,  0.,  1., 10.]])

In [88]:
m.forwardGauss()
numpy.around(m.m, 1)

array([[ 0. ,  0. ,  0. ,  0. ,  0.1,  0.1,  1. ,  0.1,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.1, -0. ,  0.2,  0. ,  1. ,  0.1,  0. ,  0. ],
       [ 0. ,  0. ,  0.1, -0. ,  0. ,  0.3,  0. ,  0. ,  1. ,  0.1,  0. ],
       [ 0. ,  0.1, -0. ,  0. , -0. ,  0.4,  0. ,  0. ,  0. ,  1. ,  0.1],
       [ 0.1, -0. ,  0. , -0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [89]:
m.backwardGauss()
numpy.around(m.m, 1)

array([[ 0. , -0. ,  0. , -0. ,  0.1,  0.1,  1. ,  0. ,  0. ,  0. ,  0. ],
       [-0. ,  0. , -0. ,  0.1, -0. ,  0.2,  0. ,  1. ,  0. ,  0. ,  0. ],
       [ 0. , -0. ,  0.1, -0. ,  0. ,  0.3,  0. ,  0. ,  1. ,  0. ,  0. ],
       [-0. ,  0.1, -0. ,  0. , -0. ,  0.3,  0. ,  0. ,  0. ,  1. ,  0. ],
       [ 0.1, -0. ,  0. , -0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  1. ]])

In [90]:
m[1,0]

0.08333854003957097

In [104]:
class Empty:
    pass

e = Empty()

In [107]:
not hasattr(e, "x")

True

In [138]:
a = numpy.eye(3)
a[0, 1] = 1
x = [1, 2, 3]

In [139]:
a.dot(x)

array([3., 2., 3.])

In [140]:
numpy.matmul(a, x)

array([3., 2., 3.])

In [141]:
[0] + x

[0, 1, 2, 3]